version: '3.8'
services:
  postgres:
    image: 'postgres:15'
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_pass
      POSTGRES_DB: n8n
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  n8n:
    image: 'n8nio/n8n:latest'
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n_pass
      N8N_PROTOCOL: https
      N8N_HOST: n8n.mivel.eu
      N8N_PORT: 5678
      WEBHOOK_URL: 'https://n8n.mivel.eu/'
      N8N_SECURE_COOKIE: 'true'
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: all
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      N8N_LOG_LEVEL: info
    ports:
      - '5678:5678'
    volumes:
      - 'n8n_data:/home/node/.n8n'
    depends_on:
      - postgres
    restart: unless-stopped
  ollama:
    image: 'ollama/ollama:latest'
    volumes:
      - 'ollama_data:/root/.ollama'
    environment:
      OLLAMA_HOST: 0.0.0.0
    ports:
      - '11434:11434'
  mail-classifier:
    build:
      context: ./mail-classifier
      dockerfile: Dockerfile
    environment:
      MODEL_NAME: all-MiniLM-L6-v2
      OLLAMA_URL: 'http://ollama:11434'
      TELEGRAM_CHAT_ID: 123456789
      TELEGRAM_TOKEN: '${TELEGRAM_TOKEN}'
    depends_on:
      - ollama
    restart: always
volumes:
  pgdata: null
  n8n_data: null
  ollama_data: null
